<script setup lang="ts">
import { computed, ref } from 'vue'
const width=ref(4),rob=ref(64),lanes=ref(2),frequency=ref(1.6)
const defaults={width:4,rob:64,lanes:2,frequency:1.6}
const area=computed(()=>Math.round(2.8+width.value*.65+rob.value*.025+lanes.value*.7))
const power=computed(()=>+(1.2+width.value*.33+rob.value*.009+lanes.value*.45+frequency.value*.7).toFixed(1))
const ipc=computed(()=>Math.min(+(width.value*(.52+rob.value/300)*(1+lanes.value*.08)).toFixed(2),width.value))
const score=computed(()=>Math.round(ipc.value*100/(area.value*.55+power.value*.8)))
function reset(){width.value=defaults.width;rob.value=defaults.rob;lanes.value=defaults.lanes;frequency.value=defaults.frequency}
function preset(kind:string){if(kind==='efficient'){width.value=3;rob.value=48;lanes.value=1;frequency.value=1.3}else{width.value=6;rob.value=128;lanes.value=4;frequency.value=2.2}}
</script>
<template><section class="dse"><header><div><small>DESIGN SPACE EXPLORER</small><h3>Shape the microarchitecture</h3></div><div><button @click="preset('efficient')">Efficient</button><button @click="preset('performance')">Performance</button><button @click="reset">Reset</button></div></header><div class="body"><div class="sliders"><label><span>Issue width <b>{{width}}</b></span><input v-model.number="width" type="range" min="2" max="8" step="1"></label><label><span>ROB entries <b>{{rob}}</b></span><input v-model.number="rob" type="range" min="32" max="160" step="16"></label><label><span>Vector lanes <b>{{lanes}}</b></span><input v-model.number="lanes" type="range" min="1" max="8" step="1"></label><label><span>Frequency <b>{{frequency.toFixed(1)}} GHz</b></span><input v-model.number="frequency" type="range" min="1" max="2.5" step=".1"></label></div><div class="metrics"><article><small>PERFORMANCE</small><strong>{{ipc}}</strong><span>IPC</span><i :style="{height:`${ipc/8*100}%`}"/></article><article><small>AREA</small><strong>{{area}}</strong><span>mm²</span><i :style="{height:`${area/16*100}%`}"/></article><article><small>POWER</small><strong>{{power}}</strong><span>W</span><i :style="{height:`${power/12*100}%`}"/></article></div></div><footer><div><span>EFFICIENCY SCORE</span><b>{{score}}</b></div><p :class="{good:score>25}">{{score>25?'✓ balanced configuration':'△ performance comes at a cost'}}</p><code>W{{width}} · R{{rob}} · V{{lanes}} · {{frequency.toFixed(1)}}G</code></footer></section></template>
<style scoped>
.dse{color:#edf7ff;background:#0a1320;border:1px solid #293950;border-radius:18px;padding:22px 25px;font-family:Inter,system-ui}header{display:flex;justify-content:space-between;align-items:center}header small{color:#55e6d6;font-size:10px;letter-spacing:.18em;font-weight:800}h3{margin:4px 0;font-size:20px}button{background:#142236;border:1px solid #34465f;color:#c9d6e7;border-radius:7px;padding:6px 10px;margin-left:6px;cursor:pointer}button:hover{color:#55e6d6;border-color:#55e6d6}.body{display:grid;grid-template-columns:1fr 1.25fr;gap:22px;margin:18px 0}.sliders{background:#0e1a2a;border:1px solid #26364c;border-radius:12px;padding:15px 18px}.sliders label{display:block;margin:0 0 13px}.sliders label:last-child{margin:0}.sliders span{display:flex;justify-content:space-between;color:#91a2b8;font-size:11px}.sliders b{color:#e9f5ff}input{width:100%;height:8px;accent-color:#55e6d6}.metrics{display:flex;gap:10px}.metrics article{position:relative;overflow:hidden;flex:1;background:#0e1a2a;border:1px solid #26364c;border-radius:12px;padding:14px;display:flex;flex-direction:column;justify-content:center;text-align:center}.metrics small{color:#8da0b7;font-size:9px;letter-spacing:.12em}.metrics strong{font-size:30px;margin-top:8px}.metrics span{color:#8da0b7;font-size:10px}.metrics i{position:absolute;bottom:0;left:0;right:0;background:linear-gradient(#55e6d622,#55e6d608);border-top:1px solid #55e6d655;z-index:0;transition:.3s}.metrics :is(small,strong,span){z-index:1}footer{display:flex;align-items:center;gap:18px;background:#ffffff08;border-radius:10px;padding:10px 14px}footer div{display:flex;align-items:center;gap:9px}footer div span{color:#8da0b7;font-size:9px;letter-spacing:.1em}footer div b{color:#55e6d6;font-size:21px}footer p{margin:0;flex:1;color:#fbbf24;font-size:10px}.good{color:#2dd4bf}footer code{color:#a6b6ca;font-size:9px}
</style>
