<script setup>
import { computed, onMounted, ref } from 'vue'
import { filterTimeline, readArtifactResponse } from './session2Models.mjs'
const fallback=[{sequence_id:573,opcode:'TASSIGN',engine:'Scalar',start:0,end:1},{sequence_id:575,opcode:'TLOAD',engine:'TMA',start:2,end:18},{sequence_id:579,opcode:'TEXTRACT',engine:'Vector',start:20,end:28},{sequence_id:587,opcode:'TMATMUL',engine:'Cube',start:412,end:544},{sequence_id:589,opcode:'TMATMUL_ACC',engine:'Cube',start:545,end:677},{sequence_id:1134,opcode:'TSTORE',engine:'TMA',start:10993,end:11025}]
const events=ref(fallback),opcode=ref('all'),engine=ref('all'),artifactState=ref('teaching sample'),visible=computed(()=>filterTimeline(events.value,{opcode:opcode.value,engine:engine.value}))
onMounted(async()=>{try{const response=await fetch(`${import.meta.env.BASE_URL}experiments/artifacts/11/qproj_timeline.csv`);const text=await readArtifactResponse(response,value=>value.text());const [head,...lines]=text.trim().split('\n');const keys=head.split(',');events.value=lines.map(line=>Object.fromEntries(keys.map((key,i)=>[key,line.split(',')[i]]))).map(x=>({sequence_id:Number(x.sequence_id),opcode:x.opcode,engine:x.engine[0]+x.engine.slice(1).toLowerCase(),start:Number(x.issue_cycle),end:Number(x.engine_complete_cycle)}));artifactState.value='checked reference_replay artifact'}catch{events.value=fallback;artifactState.value='artifact unavailable · teaching sample'}})
</script>
<template><section class="timeline arch-overlay" aria-label="Offline evidence timeline"><header><b>OFFLINE TIMELINE · {{artifactState}}</b><label>opcode <select v-model="opcode"><option>all</option><option v-for="value in [...new Set(events.map(e=>e.opcode))]" :key="value">{{value}}</option></select></label><label>engine <select v-model="engine"><option>all</option><option v-for="value in [...new Set(events.map(e=>e.engine))]" :key="value">{{value}}</option></select></label></header><div class="tracks"><div v-for="event in visible" :key="event.sequence_id"><strong>{{event.engine}}</strong><span :style="{'--left':Math.min(60,event.start/180),'--width':Math.min(20,Math.max(15,(event.end-event.start)/10))}"><b>#{{event.sequence_id}} {{event.opcode}}</b><small>{{event.start}}→{{event.end}}</small></span></div></div><footer>Perfetto / Kanata-style inspection · local CSV · opcode and engine filters</footer></section></template>
<style scoped>.timeline{right:0;bottom:-18px;width:760px;padding:16px;border-radius:20px;transform:scale(.8);transform-origin:bottom right}.timeline header{display:flex;align-items:center;gap:12px;color:#9fb7ca;font-size:12px}.timeline header>b{color:#17d9ff;margin-right:auto}.timeline select{margin-left:5px;padding:3px;background:#06152b;color:#fff;border:1px solid #17d9ff55}.tracks{display:grid;gap:6px;margin:14px 0;overflow:hidden}.tracks>div{position:relative;height:27px;border-radius:6px;background:linear-gradient(90deg,#ffffff0a 1px,transparent 1px);background-size:10% 100%}.tracks strong{position:absolute;left:5px;top:7px;color:#adc3d8;font-size:12px}.tracks span{position:absolute;left:calc(76px + var(--left)*1%);width:calc(var(--width)*1%);padding:4px 7px;border-left:3px solid #ffbe00;border-radius:4px;background:#ffbe0025;font-size:12px;white-space:nowrap}.tracks small{margin-left:6px;color:#9fb7ca;font-size:12px}.timeline footer{color:#8da8be;font-size:12px}</style>
