<script setup lang="ts">
import { computed, onBeforeUnmount, ref } from 'vue'
const items=[
  {tag:'COURSE',title:'NDF-SRC-001',id:'docs/NDF.md',c:'#60a5fa'},
  {tag:'PTO',title:'BundleIsActive',id:'asl/bundle/state.asl:143',c:'#38bdf8'},
  {tag:'TEST',title:'assert BundleIsActive',id:'tests/asl/bundle-tests.asl:99',c:'#c084fc'},
]
const active=ref(0),playing=ref(false);let timer:ReturnType<typeof setInterval>|undefined
const coverage=computed(()=>Math.round((active.value+1)/items.length*100))
function step(){active.value=(active.value+1)%items.length}function stop(){playing.value=false;if(timer)clearInterval(timer);timer=undefined}function play(){if(playing.value)return;playing.value=true;timer=setInterval(step,950)}function reset(){stop();active.value=0}onBeforeUnmount(stop)
</script>
<template><section class="ndf"><header><div><small>NDF TRACEABILITY · PTO EXAMPLE</small><h3>One semantic claim, one executable test.</h3></div><div><button @click="step">Step</button><button @click="playing?stop():play()">{{playing?'Pause':'Play'}}</button><button @click="reset">Reset</button></div></header><div class="chain"><button v-for="(item,i) in items" :key="item.tag" class="node" :class="{active:i===active,passed:i<active}" :style="{'--c':item.c}" @click="active=i"><span>{{item.tag}}</span><strong>{{item.title}}</strong><small>{{item.id}}</small><i v-if="i<items.length-1">→</i></button></div><div class="detail"><div class="ring" :style="{'--pct':`${coverage*3.6}deg`}"><b>{{coverage}}%</b><small>linked</small></div><div><small>VERIFIABLE LOCATION</small><h4>{{items[active].tag}} · {{items[active].title}}</h4><p>{{items[active].id}}</p></div><code>NDF-SRC-001</code></div></section></template>
<style scoped>
.ndf{color:#edf7ff;background:linear-gradient(135deg,#0b1422,#101827);border:1px solid #293950;border-radius:18px;padding:22px 25px;font-family:Inter,system-ui;position:absolute;right:0;bottom:0;width:900px;transform:scale(.56);transform-origin:bottom right}header{display:flex;justify-content:space-between;align-items:center}header small,.detail>div>small{color:#55e6d6;font-size:12px;letter-spacing:.17em;font-weight:800}h3{margin:4px 0;font-size:20px}header button{background:#142236;border:1px solid #34465f;color:#c9d6e7;border-radius:7px;padding:6px 11px;margin-left:6px;cursor:pointer}.chain{display:flex;align-items:center;justify-content:center;gap:70px;margin:24px 0}.node{position:relative;width:24%;min-height:100px;background:#111d2e;border:1px solid #34445b;border-radius:11px;color:#8495aa;padding:12px 8px;display:flex;flex-direction:column;align-items:center;gap:7px;cursor:pointer}.node span{color:var(--c);font-size:12px;font-weight:900;letter-spacing:.14em}.node strong{font-size:12px;color:#d5e0ec}.node small{font: 12px ui-monospace,monospace}.node i{position:absolute;right:-50px;top:40px;color:#53647a;font-style:normal;font-size:18px}.node.active,.node.passed{border-color:var(--c);box-shadow:0 0 17px color-mix(in srgb,var(--c) 35%,transparent)}.node.active{transform:translateY(-4px)}.detail{display:grid;grid-template-columns:74px 1fr auto;gap:18px;align-items:center;background:#ffffff08;border:1px solid #ffffff0d;border-radius:12px;padding:13px 17px}.ring{--pct:0deg;width:62px;height:62px;border-radius:50%;display:grid;place-content:center;background:radial-gradient(circle,#101a29 56%,transparent 58%),conic-gradient(#55e6d6 var(--pct),#2b394d 0);text-align:center}.ring b{font-size:15px}.ring small{font-size:12px;color:#90a2b8}.detail h4{margin:4px 0;font-size:14px}.detail p{margin:0;color:#92a3b8;font-size:12px}.detail code{color:#55e6d6;background:#0a121e;padding:7px 9px;border-radius:6px;font-size:12px}
</style>
