<script setup>
import { computed, onMounted, ref } from 'vue'
import { readArtifactResponse, selectSweepPoint } from './session2Models.mjs'
const artifact=ref(null),selectedId=ref(''),artifactState=ref('loading checked artifact')
const points=computed(()=>artifact.value?.points??[])
const point=computed(()=>artifact.value&&selectedId.value?selectSweepPoint(artifact.value,selectedId.value):null)
onMounted(async()=>{try{const response=await fetch(`${import.meta.env.BASE_URL}experiments/artifacts/11/qproj_sweep.json`);artifact.value=await readArtifactResponse(response,value=>value.json());selectedId.value=artifact.value.points[0]?.id??'';artifactState.value='checked reference_replay OFAT'}catch{artifact.value=null;selectedId.value='';artifactState.value='artifact unavailable · no q_proj evidence'}})
</script>
<template><section class="sweep arch-overlay" aria-label="Parameter sweep"><header><b>q_proj checked OFAT points</b><span>{{artifactState}}</span></header><label class="picker">point <select v-model="selectedId" :disabled="!points.length"><option v-if="!points.length" value="">unavailable</option><option v-for="item in points" :key="item.id" :value="item.id">{{item.id}} · {{item.parameter}}={{item.value}} {{item.unit}}</option></select></label><div v-if="point" class="result"><span>parameter<b>{{point.parameter}}</b></span><span>value<b>{{point.value}} {{point.unit}}</b></span><span>simulated cycles<b>{{point.simulatedCycles}}</b></span><span>bottleneck signal<b>{{point.bottleneckSignal}}</b></span><span>speedup vs reference<b>{{point.speedup}}×</b></span></div><div v-else class="unavailable">artifact unavailable · no q_proj evidence displayed</div><footer>one-factor-at-a-time reference replay · sensitivity only · not architectural equivalence</footer></section></template>
<style scoped>.sweep{right:0;bottom:0;width:760px;padding:16px;border-radius:20px}.sweep header{display:flex;justify-content:space-between;color:#9fb7ca;font-size:12px}.sweep header b{color:#17d9ff}.picker{display:grid;grid-template-columns:42px 1fr;align-items:center;gap:8px;margin:14px 0;color:#adc3d8;font-size:12px}.picker select{padding:7px;background:#06152b;color:#fff;border:1px solid #17d9ff55}.result{display:grid;grid-template-columns:repeat(5,1fr);gap:7px}.result span{padding:8px;border:1px solid #ffffff18;border-radius:8px;color:#8da8be;font-size:12px}.result b{display:block;margin-top:4px;color:#ffbe00;font-size:12px;overflow-wrap:anywhere}.unavailable{padding:18px;border:1px solid #f16bb566;border-radius:8px;color:#f16bb5;font-size:12px}.sweep footer{margin-top:10px;color:#f16bb5;font-size:12px}</style>
