<script setup lang="ts">
import { computed, onBeforeUnmount, ref } from 'vue'
type Point={name:string;area:number;perf:number;power:number;frontier?:boolean}
const points:Point[]=[{name:'Tiny',area:3.2,perf:1.6,power:2.1,frontier:true},{name:'Eco',area:4.8,perf:2.9,power:3.0,frontier:true},{name:'Balanced',area:6.9,perf:4.4,power:4.8,frontier:true},{name:'Wide',area:9.6,perf:5.5,power:7.2,frontier:true},{name:'Turbo',area:12.5,perf:6.1,power:10.4,frontier:true},{name:'A',area:6.1,perf:2.5,power:5.1},{name:'B',area:8.4,perf:3.7,power:6.6},{name:'C',area:10.5,perf:4.3,power:8.9}]
const revealed=ref(1),selected=ref(0),playing=ref(false),frontierOnly=ref(false);let timer:ReturnType<typeof setInterval>|undefined
const visible=computed(()=>points.filter((p,i)=>i<revealed.value&&(!frontierOnly.value||p.frontier)))
const selectedPoint=computed(()=>points[selected.value])
const x=(v:number)=>60+(v-2)/11*600, y=(v:number)=>260-(v-1)/5.5*220
const frontierPath=computed(()=>points.filter(p=>p.frontier).map((p,i)=>`${i?'L':'M'}${x(p.area)} ${y(p.perf)}`).join(' '))
function step(){if(revealed.value<points.length){revealed.value++;selected.value=revealed.value-1}else{revealed.value=1;selected.value=0}}function stop(){playing.value=false;if(timer)clearInterval(timer);timer=undefined}function play(){if(playing.value)return;playing.value=true;timer=setInterval(step,700)}function reset(){stop();revealed.value=1;selected.value=0;frontierOnly.value=false}onBeforeUnmount(stop)
</script>
<template><section class="pareto"><header><div><small>PARETO FRONTIER</small><h3>Performance has a price.</h3></div><div><button @click="step">Step</button><button @click="playing?stop():play()">{{playing?'Pause':'Play'}}</button><button @click="frontierOnly=!frontierOnly" :class="{on:frontierOnly}">Highlight</button><button @click="reset">Reset</button></div></header><div class="layout"><svg viewBox="0 0 700 300"><g class="grid"><line v-for="i in 6" :key="'h'+i" x1="60" :y1="40+(i-1)*44" x2="660" :y2="40+(i-1)*44"/><line v-for="i in 7" :key="'v'+i" :x1="60+(i-1)*100" y1="40" :x2="60+(i-1)*100" y2="260"/></g><text class="axis" x="350" y="292">AREA →</text><text class="axis" transform="translate(14 185) rotate(-90)">PERFORMANCE →</text><path class="frontier" :d="frontierPath"/><g v-for="p in visible" :key="p.name" class="point" :class="{selected:selectedPoint===p,dim:frontierOnly&&!p.frontier}" @click="selected=points.indexOf(p)"><circle :cx="x(p.area)" :cy="y(p.perf)" :r="selectedPoint===p?9:6"/><text :x="x(p.area)+9" :y="y(p.perf)-9">{{p.name}}</text></g></svg><aside><small>SELECTED DESIGN</small><h4>{{selectedPoint.name}}</h4><div><span>Performance</span><b>{{selectedPoint.perf}} IPC</b></div><div><span>Area</span><b>{{selectedPoint.area}} mm²</b></div><div><span>Power</span><b>{{selectedPoint.power}} W</b></div><p :class="{optimal:selectedPoint.frontier}">{{selectedPoint.frontier?'● PARETO-OPTIMAL':'○ DOMINATED'}}</p></aside></div><footer><span>{{revealed}} / {{points.length}} candidates evaluated</span><i/><b>Move up and left</b><code>maximize IPC · minimize area</code></footer></section></template>
<style scoped>
.pareto{color:#edf7ff;background:#0a1320;border:1px solid #293950;border-radius:18px;padding:21px 24px;font-family:Inter,system-ui}header{display:flex;justify-content:space-between;align-items:center}header small,aside>small{color:#55e6d6;font-size:10px;letter-spacing:.18em;font-weight:800}h3{margin:4px 0;font-size:20px}button{background:#142236;border:1px solid #34465f;color:#c9d6e7;border-radius:7px;padding:6px 9px;margin-left:5px;cursor:pointer}button:hover,button.on{color:#55e6d6;border-color:#55e6d6}.layout{display:grid;grid-template-columns:1fr 165px;gap:13px;margin-top:12px}svg{width:100%;height:300px;background:#0e1928;border:1px solid #24344a;border-radius:11px}.grid line{stroke:#26364a;stroke-width:1}.axis{fill:#8799b0;text-anchor:middle;font-size:10px;letter-spacing:.13em}.frontier{fill:none;stroke:#55e6d688;stroke-width:2;stroke-dasharray:6 5}.point{cursor:pointer}.point circle{fill:#60738d;stroke:#0e1928;stroke-width:3;transition:.2s}.point text{fill:#9aacbf;font-size:10px}.point.selected circle,.point:hover circle{fill:#55e6d6;filter:drop-shadow(0 0 6px #55e6d6)}.point.selected text{fill:#e9f7ff;font-weight:800}.point.dim{opacity:.12}aside{background:#101c2c;border-left:3px solid #55e6d6;border-radius:10px;padding:17px 14px}aside h4{font-size:22px;margin:9px 0 16px}aside div{display:flex;justify-content:space-between;border-bottom:1px solid #26364a;padding:8px 0;font-size:10px;color:#91a3ba}aside div b{color:#dce8f6}aside p{color:#fb7185;font-size:10px;font-weight:900;margin-top:18px}.optimal{color:#2dd4bf}footer{display:flex;align-items:center;gap:10px;color:#91a3ba;font-size:10px;margin-top:10px}footer i{height:1px;background:#33455d;flex:1}footer b{color:#55e6d6}footer code{color:#adbdcf}
</style>
