<script setup lang="ts">
import { computed, onBeforeUnmount, ref } from 'vue'
const props=withDefaults(defineProps<{cycles?:number}>(),{cycles:8})
const cursor=ref(0),playing=ref(false);let timer:ReturnType<typeof setInterval>|undefined
const rows=[{name:'valid',bits:[0,1,1,1,0,1,1,0],c:'#38bdf8'},{name:'ready',bits:[1,0,1,1,1,0,1,1],c:'#fbbf24'},{name:'fire',bits:[0,0,1,1,0,0,1,0],c:'#2dd4bf'}]
const shown=computed(()=>rows.map(r=>({...r,bits:Array.from({length:props.cycles},(_,i)=>r.bits[i%r.bits.length])})))
function points(bits:number[]){const x0=112,w=68,hi=16,lo=44;let d=`M${x0} ${bits[0]?hi:lo}`;bits.forEach((b,i)=>{const x=x0+i*w,nx=x+w;d+=` H${nx}${i<bits.length-1?` V${bits[i+1]?hi:lo}`:''}`});return d}
function step(){cursor.value=(cursor.value+1)%props.cycles}function stop(){playing.value=false;if(timer)clearInterval(timer);timer=undefined}function play(){if(playing.value)return;playing.value=true;timer=setInterval(step,700)}function reset(){stop();cursor.value=0}onBeforeUnmount(stop)
</script>
<template><section class="timing"><header><div><small>HANDSHAKE TIMING</small><h3>Queue transfer waveform</h3></div><div><button @click="step">Step</button><button @click="playing?stop():play()">{{playing?'Pause':'Play'}}</button><button @click="reset">Reset</button></div></header><div class="chart"><div class="ruler"><span></span><b v-for="i in cycles" :key="i">C{{i-1}}</b></div><div v-for="row in shown" :key="row.name" class="wave"><strong :style="{color:row.c}">{{row.name}}</strong><svg :viewBox="`0 0 ${cycles*68} 60`" preserveAspectRatio="none"><g v-for="i in cycles" :key="i"><line :x1="(i-1)*68" y1="0" :x2="(i-1)*68" y2="60"/></g><path :d="points(row.bits)" :transform="'translate(-112 0)'" :style="{stroke:row.c}"/></svg></div><div class="cursor" :style="{left:`calc(112px + (100% - 112px) * ${cursor}/${cycles})`}"/><div class="transfer"><span v-for="(b,i) in shown[2].bits" :key="i" :class="{on:b}">{{b?'TRANSFER':'STALL'}}</span></div></div><p class="note"><b>fire = valid ∧ ready</b><span>Cycle {{cursor}} · {{shown[2].bits[cursor]?'payload accepted':'back-pressure holds payload'}}</span></p></section></template>
<style scoped>
.timing{color:#edf6ff;background:#0a1320;border:1px solid #293950;border-radius:18px;padding:21px 24px;font-family:Inter,system-ui}header{display:flex;justify-content:space-between;align-items:center}header small{color:#55e6d6;font-size:12px;letter-spacing:.18em;font-weight:800}h3{margin:4px 0;font-size:20px}button{background:#142236;border:1px solid #34465f;color:#c9d7e8;border-radius:7px;padding:6px 11px;margin-left:6px;cursor:pointer}button:hover{color:#55e6d6;border-color:#55e6d6}.chart{position:relative;margin-top:15px;background:#0e1928;border:1px solid #223249;border-radius:12px;padding:8px 0 11px;overflow:hidden}.ruler,.wave,.transfer{display:grid;grid-template-columns:112px 1fr}.ruler>b{display:none}.ruler{grid-template-columns:112px repeat(v-bind(cycles),1fr);height:26px}.ruler b{display:block;color:#8294aa;font-size:12px;text-align:left}.wave{height:60px;align-items:center}.wave strong{font:700 12px ui-monospace,monospace;padding-left:22px}.wave svg{width:100%;height:60px}.wave line{stroke:#26364a;stroke-width:1}.wave path{fill:none;stroke-width:3;vector-effect:non-scaling-stroke}.cursor{position:absolute;top:25px;bottom:31px;width:2px;background:#fb7185;box-shadow:0 0 10px #fb7185;transition:left .25s}.transfer{grid-template-columns:112px repeat(v-bind(cycles),1fr);padding-top:3px}.transfer span{font-size:12px;text-align:center;color:#8294aa}.transfer .on{color:#2dd4bf;font-weight:900}.note{display:flex;justify-content:space-between;background:#ffffff08;border-radius:8px;padding:9px 13px;margin:12px 0 0;color:#8fa0b6;font-size:12px}.note b{color:#55e6d6}
.timing{position:absolute;right:0;bottom:0;width:900px;transform:scale(.54);transform-origin:bottom right}
</style>
