<script setup lang="ts">
import { computed, onBeforeUnmount, ref } from 'vue'
const rows=[
 {cycle:104,ref:'ADD x7, x2, x4',dut:'ADD x7, x2, x4',ok:true},{cycle:105,ref:'ST  [x8+0x10], x7',dut:'ST  [x8+0x10], x7',ok:true},{cycle:106,ref:'BR  x7, +0x18',dut:'BR  x7, +0x18',ok:true},{cycle:107,ref:'LD  x9, [x8+0x20]',dut:'LD  x9, [x8+0x18]',ok:false},{cycle:108,ref:'MUL x10, x9, x3',dut:'— pipeline flushed —',ok:false},{cycle:109,ref:'RETIRE block #31',dut:'STALL waiting LSU',ok:false},
]
const cursor=ref(0),playing=ref(false),mismatchOnly=ref(false);let timer:ReturnType<typeof setInterval>|undefined
const visible=computed(()=>mismatchOnly.value?rows.filter(r=>!r.ok):rows)
function step(){cursor.value=(cursor.value+1)%visible.value.length}function stop(){playing.value=false;if(timer)clearInterval(timer);timer=undefined}function play(){if(playing.value)return;playing.value=true;timer=setInterval(step,800)}function reset(){stop();cursor.value=0;mismatchOnly.value=false}onBeforeUnmount(stop)
</script>
<template><section class="trace"><header><div><small>DIFFERENTIAL TRACE</small><h3>Reference ↔ RTL comparator</h3></div><div class="controls"><button @click="step">Step</button><button @click="playing?stop():play()">{{playing?'Pause':'Play'}}</button><button @click="reset">Reset</button></div></header><div class="toolbar"><span><i/> aligned through cycle 106</span><label><input v-model="mismatchOnly" type="checkbox" @change="cursor=0"> mismatches only</label></div><div class="grid"><div class="head">cycle</div><div class="head">REFERENCE MODEL</div><div class="head">RTL / DUT</div><template v-for="(row,i) in visible" :key="row.cycle"><div class="cell cycle" :class="{active:i===cursor,bad:!row.ok}">{{row.cycle}} <b>{{row.ok?'✓':'!'}}</b></div><code class="cell" :class="{active:i===cursor,bad:!row.ok}">{{row.ref}}</code><code class="cell" :class="{active:i===cursor,bad:!row.ok}">{{row.dut}}</code></template></div><footer><b v-if="!visible[cursor]?.ok">FIRST DIVERGENCE</b><span>cycle {{visible[cursor]?.cycle}} · {{visible[cursor]?.ok?'architectural states agree':'address-generation mismatch'}}</span></footer></section></template>
<style scoped>
.trace{color:#edf6ff;background:#0b1421;border:1px solid #2a394f;border-radius:18px;padding:21px 24px;font-family:Inter,system-ui}header,.toolbar,footer{display:flex;justify-content:space-between;align-items:center}header small{color:#55e6d6;font-size:12px;letter-spacing:.18em;font-weight:800}h3{margin:4px 0;font-size:20px}button{background:#142236;border:1px solid #34465f;color:#cad6e6;border-radius:7px;padding:6px 11px;margin-left:6px;cursor:pointer}button:hover{color:#55e6d6;border-color:#55e6d6}.toolbar{font-size:12px;color:#8190a6;margin:14px 0 7px}.toolbar i{display:inline-block;width:6px;height:6px;border-radius:50%;background:#2dd4bf;box-shadow:0 0 7px #2dd4bf}.toolbar input{accent-color:#fb7185}.grid{display:grid;grid-template-columns:72px 1fr 1fr;border:1px solid #2a394e;border-radius:10px;overflow:hidden}.head{background:#152237;color:#6f8198;font-size:12px;letter-spacing:.11em;padding:8px 11px}.cell{padding:9px 11px;border-top:1px solid #233248;background:#0e1928;color:#b9c8db;font-size:12px;transition:.2s}.cell:nth-child(3n+2){border-left:1px solid #233248;border-right:1px solid #233248}.cycle{color:#71839a;display:flex;justify-content:space-between}.cycle b{color:#2dd4bf}.cell.active{background:#17263a;color:#fff;box-shadow:inset 0 2px #55e6d6}.cell.bad{background:#2c1822;color:#fecdd3}.cycle.bad b{color:#fb7185}footer{margin-top:11px;background:#ffffff08;border-radius:8px;padding:9px 13px;color:#97a7ba;font-size:12px}footer b{color:#fb7185;letter-spacing:.12em}
</style>
